Reset password host
fle-internal/kolibri-instant-schools-plugin pull request #169
Opened 2020-08-04 17:37 UTC by nucleogenesis

When generating the reset password link, we previously wouldn't account for the X-Forwarded-* headers, so the link would be generated improperly.

Changes:

In the plugin settings file, add the `USE_X_FORWARDED_HOST|PORT` settings and set to `True`

This also involves setting nginx settings that forward the settings in the nginx config:

```
proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-Server $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

2020-08-05 19:00 UTC, jredrejo requested changes
I am afraid these changes don't work . For context: 
![image](https://user-images.githubusercontent.com/1008178/89452888-aac29d00-d75e-11ea-803a-d0ed34b61f8c.png)

2020-08-05 19:00 UTC, jredrejo commented on kolibri_instant_schools_plugin/auth/api.py
> +        baseurl = "{scheme}://{host}".format(scheme=request.scheme, host=request.get_host())
`get_host` is still retrieving kolibri

2020-08-05 20:41 UTC, indirectlylit commented
@jredrejo if you have a chance next week, would you mind taking over this PR?

2020-08-06 16:37 UTC, jredrejo commented
@indirectlylit I have it's solved now, can you or @rtibbles take a look?

2020-08-06 17:10 UTC, jredrejo approved these changes
This code changes are ok, but the current VF_IS nginx configuration needs to be changed:
```
         proxy_connect_timeout 300;
         proxy_read_timeout 300;
         #proxy_redirect <http://kolibri> <https://kolibri>;
-        proxy_set_header X-Forwarded-Host $host:$server_port;
+        # proxy_set_header X-Forwarded-Host $host:$server_port;
+        proxy_set_header X-Forwarded-Host $host;  # allows django to determine the name/addr of the server that the client originally connected to (see request.get_host())
+        proxy_set_header X-Forwarded-Port $server_port;  # same idea as above, but for port number (see request.get_port())
         proxy_set_header X-Forwarded-Server $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

Before:
![antes](https://user-images.githubusercontent.com/1008178/89561905-7b249b00-d819-11ea-8cd5-78abd576098b.png)
After:
![after](https://user-images.githubusercontent.com/1008178/89561881-72cc6000-d819-11ea-987c-b5c3ed7c64a0.png)

2020-08-06 18:04 UTC, rtibbles approved these changes

2020-08-12 13:18 UTC, merged